### PR TITLE
Updated to handle generic key and value.

### PR DESCRIPTION
**Pull request by Fraser999**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/chunk_store/19)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @madadam

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
r?  @dirvine

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/chunk_store/19#-:-KFfYrbNl6Ba-_FG-oNh:-417577783)_

**Comment by dirvine** [comment]
Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/chunk_store.rs, line 207 [r1]](https://reviewable.io:443/reviews/maidsafe/chunk_store/19#-KFf_NGZcxkbiEX280MH:-KFf_NGZcxkbiEX280MI:1774828737) ([raw file](https://github.com/maidsafe/chunk_store/blob/c7bbaf50387a63394ee5e2333b6d274d7d255f5c/src/chunk_store.rs#L207)):_
What was the rationale for this name change ? 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/chunk_store/19)_

**Comment by dirvine** [comment]
Reviewed 2 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/chunk_store/19)_

**Comment by Fraser999** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/chunk_store.rs, line 207 [r1]](https://reviewable.io:443/reviews/maidsafe/chunk_store/19#-KFf_NGZcxkbiEX280MH:-KFf_ok6ygk90-y1ElTG:-430428451) ([raw file](https://github.com/maidsafe/chunk_store/blob/c7bbaf50387a63394ee5e2333b6d274d7d255f5c/src/chunk_store.rs#L207)):_
The most similar function before was `to_hex_string()`.  That returned  a`String` which was then used in a couple of different places to create a path.  This new function returns the full path as a `PathBuf` to the chunk on disk.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/chunk_store/19)_

**Comment by dirvine** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/chunk_store.rs, line 207 [r1]](https://reviewable.io:443/reviews/maidsafe/chunk_store/19#-KFf_NGZcxkbiEX280MH:-KFfcI5FSQ-m75RekzNQ:-2122725289) ([raw file](https://github.com/maidsafe/chunk_store/blob/c7bbaf50387a63394ee5e2333b6d274d7d255f5c/src/chunk_store.rs#L207)):_
That makes sense. Cheers

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/chunk_store/19)_

**Pull request merged**
